### ISSUE TITLE
Support for non-physical keys?

### ISSUE THREAD

**Issue by anaseto** [VedVid/RogueRobsTrains#2] opened 2019-04-07 16:42 UTC
Hi!

I've been playing Rogue Robs Trains, and as a non-qwerty user, the use of physical keys has confused me a little at first : I don't know if it's a limitation of bearlibterminal, but otherwise, using character input instead of physical input for keys representing characters would be nice.

BTW, nice little game, easy to get into and quite fun! I don't know if you have plans to develop it further from the 7DRL version, but the concept is nice :-)

**Comment by VedVid** [comment] 2019-04-09 00:42
Hello, I'm glad you had fun playing RRT :) 

 I'm not sure if I understand "physical keys" term - I'd need to make some research. Could you explain what did you find confusing about controls?

 If I remember correctly, BearLibTerminal itself uses ascii character codes to handle input.

**Comment by anaseto** [comment] 2019-04-09 07:53
For keys corresponding to characters, there are two ways of handling them, either inspecting which physical key it corresponds too (what you are doing), or using the character codes. With the first approach, it means that, for example, `TK_R` will always be the key at this position in an US qwerty keyboard (in the french dvorak layout I use it corresponds to `o` instead of `r`).

Here's [a diff](https://github.com/anaseto/RogueRobsTrains/commit/ee12b16f9c57f5a7ae22f5c60abe9c20e412b5f7) which implements what I say, using `TK_WCHAR` to get the code point rune `r`, feel free to do as you wish with it :-) 

Of course, this means that in some keyboard layouts the WASD keys will not be in a sensible position, but at least they're where you expect, and it's always possible to use the numpad or HJKL for people having other keyboard layouts or to switch temporally layout to US qwerty if they really prefer in their system options.

**Comment by VedVid** [comment] 2019-04-09 10:03
Ah, I see... I was terribly confused as I thought that scan codes are attached to letter, no key position. I learnt something new today.

> this means that in some keyboard layouts the WASD keys will not be in a sensible position

and vi keys. Yeah, it may pose a problem. But on the other hand, there are arrows and numpad available as well. Also, at some point, I want to allow customizing controls. To make things official, feel free to send pr to development branch ;) That said, I can confirm already that your implementation works well for me.

I doubt I'm going to develop RRT further. I'm working (not very intensively, though) on bugfixes - but there is one nasty bug I just can't track! Some minor quality-of-life improvements are on roadmap as well. But the problem is that, I'm doing bad job as programmer working under time pressure, and this codebase is just mess. On the other hand, I'm really pleased with core mechanics, and I'm planning to use it in another simple wild west roguelike...

**Comment by anaseto** [comment] 2019-04-09 10:31
> feel free to send pr to development branch ;)

Done !

I too am not very good under time pressure. That's the reason I haven't yet participated in a 7DRL, even if I'd like too, so I understand the feeling! But even if part of the code is a little messy, it's not so large that nothing could be done if at some point you really feel like it :-) It's still easy enough to get into to the code, that I did it without prior knowledge today.

**Comment by VedVid** [comment] 2019-04-09 11:57
> Done !

Merged! :) 

I was considering to develop this game further, but honestly I don't think it would scale up well. The plan is to use RRT's mechanics into game based on my another 7drl idea, following "clean village from bandits" trope.

**Closed as completed by VedVid** 2019-04-09 11:57 UTC
Labels: enhancement

**Comment by anaseto** [comment] 2019-04-09 12:48
Seems like a good plan :-)

**Comment by VedVid** [comment] 2019-04-16 20:10
@anaseto could you check #4 ?
